package:
  name: word_knn
  version: 1.1.0

source:
  path: .

extra:
  channels:
    - pytorch
    - conda-forge

build:
  entry_points:
    - word_knn = word_knn.__main__:main

requirements:
  build:
    - python
    - setuptools
    - faiss-cpu
    - numpy
    - flask
    - flask-restful

  run:
    - python
    - faiss-cpu
    - numpy
    - flask
    - flask-restful

about:
  home:
    https://github.com/rom1504/word_knn
